//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCactusShow2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show_cactus
    {
        public int Id_sc { get; set; }
        public Nullable<int> Id_show { get; set; }
        public Nullable<int> Id_cactus { get; set; }
        public string Prize { get; set; }
        public string Comment { get; set; }
    
        public virtual Cactus Cactus { get; set; }
        public virtual Show Show { get; set; }
    }
}
